#!/bin/zsh

# ~/.profile is only loaded when running zsh in sh compatibility mode,
# otherwise it reads .zprofile
# as well as .zshrc for interactive and .zlogin for login shells.
# Environmental variables are set here first

# Loads brew
    eval "$(/opt/homebrew/bin/brew shellenv)"



# Set Work or Personal Setting Var
    export IS_WORK=false

# Default Programs
    if type nvim >/dev/null 2>&1; then
        export EDITOR="nvim"
        export VISUAL=nvim
    else
        export EDITOR="vim"
        export VISUAL=vim
    fi

#----------------------------------------------------------------------
#                       PATH
#----------------------------------------------------------------------

# XDG Location
    export DOTFILES="$HOME/dotfiles"                 # preference
    export XDG_CONFIG_HOME="$DOTFILES/.config"       # /etc
    export XDG_DATA_HOME="$DOTFILES/.local/share"    # /usr/share
    export XDG_CACHE_HOME="$DOTFILES/.cache"         # /var/cache
	export XDG_STATE_HOME="$DOTFILES/.local/state"

# Add Work Scripts to path if on work comp
	if $IS_WORK; then
		PATH=$PATH:$DOTFILES/.local/work/bin
	fi

# Add Personal Scripts to path
    PATH=$PATH:$DOTFILES/.local/bin


# Spaceship
	export SPACESHIP_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/spaceship/spaceship.zsh"

# Cleanup for programs that don't listen to XDG SPEC :'(
    # VIMINIT will be sourced by neovim too, so I set this: XDG for NVIM & EXINIT for Vim
    export EXINIT='let $MYVIMRC="$XDG_CONFIG_HOME/vim/vimrc" | source $MYVIMRC'
    export VIMDOTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/vim"
    export GTK2_RC_FILES="${XDG_CONFIG_HOME:-$HOME/.config}/gtk-2.0/gtkrc-2.0"
    export INPUTRC="${XDG_CONFIG_HOME:-$HOME/.config}/shell/inputrc"
    export WGETRC="${XDG_CONFIG_HOME:-$HOME/.config}/wget/wgetrc"
    export ZDOTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/zsh"
    export WEECHAT_HOME="${XDG_CONFIG_HOME:-$HOME/.config}/weechat"
    export CARGO_HOME="${XDG_DATA_HOME:-$HOME/.local/share}/cargo"

    # GO Lang
    export GOPATH="${XDG_DATA_HOME:-$HOME/.local/share}/go"
    export GOBIN="${XDG_DATA_HOME:-$HOME/.local/share}/go/bin"

	# Node.js
	export N_PREFIX="${XDG_DATA_HOME:-$HOME/.local/share}/node"
	export N_CACHE_PREFIX="$XDG_CACHE_HOME"
	export N_PRESERVE_NPM=1
	export N_PRESERVE_COREPACK=1
	export NPM_CONFIG_USERCONFIG=${XDG_CONFIG_HOME:-$HOME/.config}/npm/npmrc
	export COREPACK_HOME="${XDG_DATA_HOME:-$HOME/.local}/corepack"
	export NODE_REPL_HISTORY="$XDG_STATE_HOME/node_repl/history"
	export NODE_REPL_HISTORY="$XDG_STATE_HOME/node_repl/history"

	# Add Node.js to PATH
	if [[ $PATH != *"$N_PREFIX/bin"* ]]; then
		export PATH="$PATH:$N_PREFIX/bin";
	fi

    # export TMUX_TMPDIR="$XDG_RUNTIME_DIR"

# less
    export LESSHISTFILE="${XDG_CONFIG_HOME}/less/history"
    export LESSKEY="${XDG_CONFIG_HOME}/less/keys"

# mplayer
    export MPLAYER_HOME=$XDG_CONFIG_HOME/mplayer

# subversion
    export SUBVERSION_HOME=$XDG_CONFIG_HOME/subversion

# Neovim-Remote add to Path Python3
    PATH=$HOME/.cargo/bin:$PATH


# GNUPG
	export GNUPGHOME=${XDG_CONFIG_HOME}/gnupg
	export GPG_TTY=$(tty)


export NVM_DIR="$HOME/dotfiles/.config/nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm

#----------------------------------------------------------------------
#                       FZF
#----------------------------------------------------------------------
# FZF Default command
    export FZF_DEFAULT_COMMAND='rg --files --hidden'
    export FZF_DEFAULT_OPTS='--layout=reverse --border --inline-info --height=80%'

# Preview file content using bat (https://github.com/sharkdp/bat)
    export FZF_CTRL_T_OPTS="
      --preview 'bat -n --color=always {}'
      --bind 'ctrl-/:change-preview-window(down|hidden|)'"

# Print tree structure in the preview window
    export FZF_ALT_C_OPTS="--preview 'tree -C {}'"

    export FZF_DEFAULT_OPTS=$FZF_DEFAULT_OPTS'
         --color=fg:#dedede,bg:#121212,hl:#666666
         --color=fg+:#eeeeee,bg+:#282828,hl+:#cf73e6
         --color=info:#cf73e6,prompt:#FF0000,pointer:#cf73e6
         --color=marker:#f0d50c,spinner:#cf73e6,header:#91aadf'

# export FZF_DEFAULT_OPTS=$FZF_DEFAULT_OPTS'
#     --color=fg:#ecf0c1,bg:#0f111b,hl:#00a3cc
#     --color=fg+:#ffffff,bg+:#0f111b,hl+:#b3a1e6
#     --color=info:#afaf87,prompt:#ce6f8f,pointer:#7a5ccc
#     --color=marker:#5ccc96,spinner:#7a5ccc,header:#5ccc96'
