"        _                    
"       (_)                   
" __   ___ _ __ ___  _ __ ___ 
" \ \ / / | '_ ` _ \| '__/ __|
"  \ V /| | | | | | | | | (__ 
"   \_/ |_|_| |_| |_|_|  \___|
"                             

source $XDG_CONFIG_HOME/nvim/general.vim        " General Settings point to nvim (less code duplication)
source $XDG_CONFIG_HOME/nvim/mappings.vim       " Remappings for Vim
