#!/usr/bin/env bash

# ~/macos — https://mths.be/macos
# Run without downloading:
# curl "https://raw.githubusercontent.com/pineapplegiant/dotfiles/supreme-overlord/setup/macos" | bash

# Close any open System Preferences panes, to prevent them from overriding
# settings we’re about to change
osascript -e 'tell application "System Preferences" to quit'

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until `.macos` has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

###############################################################################
# Customizations
###############################################################################

echo "Hello $(whoami)! Let's get you set up."
cd $HOME

# install homebrew https://brew.sh
echo "installing homebrew..."
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

echo "installing git..."
brew install git

# Log where we're installing stuff
echo "Hello again $(whoami)! We will be downloading your dotfiles now into:"
echo $HOME
echo "cloning dotfiles..."

git clone "https://github.com/pineapplegiant/dotfiles.git"

echo "Moving into dotfiles repo."
cd $HOME/dotfiles/setup

echo "Symlinking config into place"
echo "ln -s $HOME/dotfiles/.profile ~/.profile"
ln -s $HOME/dotfiles/.profile ~/.profile

echo "ln -s $HOME/dotfiles/.zprofile ~/.zprofile"
ln -s $HOME/dotfiles/.zprofile ~/.zprofile

echo "ln -s $HOME/dotfiles/.config/alacritty/alacritty.yml ~/.config/alacritty.yml"
ln -s $HOME/dotfiles/.config/alacritty/alacritty.yml ~/.config/alacritty.yml

echo "ln -s $HOME/dotfiles/.zprofile ~/.zprofile"
ln -s $HOME/dotfiles/.zprofile ~/.zprofile


echo "installing brew utilities, packages, spaceship prompt and all the things..."
brew bundle

###############################################################################
# General UI/UX                                                               #
###############################################################################

echo "Making system modifications:"

# Disable the sound effects on boot
sudo nvram SystemAudioVolume=" "

# Set a blazingly fast keyboard repeat rate, increased for NVIM
defaults write NSGlobalDomain KeyRepeat -int 0

# normal minimum is 15 (225 ms), normal minimum is 2 (30 ms)
defaults write -g InitialKeyRepeat -int 15 && defaults write -g KeyRepeat -int 2

# Use plain text mode for new TextEdit documents
defaults write com.apple.TextEdit RichText -int 0

# Open and save files as UTF-8 in TextEdit
defaults write com.apple.TextEdit PlainTextEncoding -int 4
defaults write com.apple.TextEdit PlainTextEncodingForWrite -int 4

# Automatically hide and show the Dock
defaults write com.apple.dock autohide -bool true

# Show icons for hard drives, servers, and removable media on the desktop
defaults write com.apple.finder ShowExternalHardDrivesOnDesktop -bool true
defaults write com.apple.finder ShowHardDrivesOnDesktop -bool false
defaults write com.apple.finder ShowMountedServersOnDesktop -bool false
defaults write com.apple.finder ShowRemovableMediaOnDesktop -bool true

# Finder: show all filename extensions
defaults write NSGlobalDomain AppleShowAllExtensions -bool true

# Finder: show status bar
defaults write com.apple.finder ShowStatusBar -bool true

# Finder: show path bar
defaults write com.apple.finder ShowPathbar -bool true

# Display full POSIX path as Finder window title
defaults write com.apple.finder _FXShowPosixPathInTitle -bool true

# When performing a search, search the current folder by default
defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"

# Set the icon size of Dock items to 50 pixels
defaults write com.apple.dock tilesize -int 50

# Change minimize/maximize window effect
defaults write com.apple.dock mineffect -string "scale"

# Minimize windows into their application’s icon
defaults write com.apple.dock minimize-to-application -bool true

# Enable spring loading for all Dock items
defaults write com.apple.dock enable-spring-load-actions-on-all-items -bool true

# Avoid creating .DS_Store files on network or USB volumes
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true
defaults write com.apple.desktopservices DSDontWriteUSBStores -bool true

# Disable disk image verification
defaults write com.apple.frameworks.diskimages skip-verify -bool true
defaults write com.apple.frameworks.diskimages skip-verify-locked -bool true
defaults write com.apple.frameworks.diskimages skip-verify-remote -bool true

# Automatically open a new Finder window when a volume is mounted
defaults write com.apple.frameworks.diskimages auto-open-ro-root -bool true
defaults write com.apple.frameworks.diskimages auto-open-rw-root -bool true
defaults write com.apple.finder OpenWindowForNewRemovableDisk -bool true

# Show indicator lights for open applications in the Dock
defaults write com.apple.dock show-process-indicators -bool true

# - Set hostname: tetsuko
#     scutil --set HostName hostname

scutil --set HostName tetsuko

echo "Done. Note that some of these changes require a logout/restart to take effect."
